services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-dev
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

volumes:
  vendor_data:
