services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app

    networks:
      - laravel

  nginx:
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
